name: CoreExample
options:
  bundleIdPrefix: com.ficklebits.dinnertime
  postGenCommand: pod install
targets:
  Example:
    type: application
    platform: "iOS"
    deploymentTarget: "14.0"
    sources: [Example]
    scheme:
      testTargets:
        - Tests
    info:
      path: "Source/Info.plist"
      properties:
        UILaunchStoryboardName: 

  Tests:
    type: bundle.unit-test
    platform: "iOS"
    deploymentTarget: "14.0"
    sources: [Tests]

